### ISSUE TITLE
Upload Data from CSV to Elasticsearch

### ISSUE THREAD

**Issue by dhaneshragu** [swciitg/IntranetSearch#1]
### Task Description

To enhance the functionality of the project, we need to create a route in the `main.py` file (located inside the `python/app` folder) for uploading data from a CSV file into Elasticsearch. We'll use the initialized Elasticsearch client for this purpose. Additionally, we should refer to the `create-index` route in the backend folder for the structure of the Elasticsearch index.

### Detailed Task

1. **Modify the store route in `main.py`**:
 - Inside `python/app` in `main.py` file `store route`, write the code for uploading this data from the df created into elasticsearch index using the intitialised elasticsearch client.
- Refer to create-index route in backend folder for the structure of index.

2. **Refer to `create-index` Structure**:
   - Refer to the structure of the Elasticsearch index used in the `create-index` route located in the backend folder.
- Index structure 
```
embeddings: {
        type: "dense_vector",
        dims: req.body.dim ? req.body.dim : 384,
        index: true,
        similarity: "cosine",
      },
      content: { type: "text" },
      url: { type: "text" },
```

3. **Hint - Bulk API for Data Upload**:
   - Use the Elasticsearch Bulk API to efficiently upload data from the CSV file into the Elasticsearch index.

**Write comments wherever possible and write clean and efficient codes.**

**Comment by NProblems** [comment]
i would like to work on this

**Comment by dhaneshragu** [comment]
> i would like to work on this

@NProblems  you are assigned on this. make sure to read the task description carefully.

**Comment by dhaneshragu** [comment]
@NProblems  since u are unresponsive, deassigning you
