### ISSUE TITLE
Improve package size in docker container

### ISSUE THREAD

**Issue by dhaneshragu** [swciitg/IntranetSearch#10]
The current docker container in `python` folder uses lots of space due to `sentence-transformers` library. 
Optimise this space if possible by making changes in `Dockerfile`.

**Comment by AtriChatterjee1** [comment]
Hey @dhaneshragu we can, definitely improve the size of the container by using slim image of the python3.9 being used in the file. If this is what you are looking for I can def link a PR

**Comment by dhaneshragu** [comment]
Sure, go ahead and attach a acreenshot of the size of the container that you manage to obtain after doing this. Also, the codebase should work properly with your changed Dockerfile.
Note : I'll merge the PR only if significant reduction in size of container is achieved.

**Comment by AtriChatterjee1** [comment]
using the slim tag, reduces the size by ~870MB, I am trying, if there are anyother ways to reduce the size further

(none is the previous image of intranet search)
![image](https://github.com/swciitg/IntranetSearch/assets/112633183/67413ece-e0aa-4b68-9db7-ba591591b34a)

**Comment by dhaneshragu** [comment]
> using the slim tag, reduces the size by ~870MB, I am trying, if there are anyother ways to reduce the size further
> 
> (none is the previous image of intranet search) ![image](https://user-images.githubusercontent.com/112633183/271908655-67413ece-e0aa-4b68-9db7-ba591591b34a.png)

Try to achieve more significant reduction. (as 870MB is less in comparison with 5.8GB size)

**Comment by dhaneshragu** [comment]
@AtriChatterjee1 , any improvements?

**Comment by AtriChatterjee1** [comment]
Tried multistage builds, but that too didn't reduce the container size that significantly

**Comment by dhaneshragu** [comment]
Ah okay, try some other method or try to link a PR with the Dockerfile where you have achieved the greatest reduction. **The code base must run properly within the container**.
