### ISSUE TITLE
Clean the crawled content before saving it to mongodb

### ISSUE THREAD

**Issue by dhaneshragu** [swciitg/IntranetSearch#16]
- The cleaned content, especially headings have lot of newline and trailing and leading backspace, which might introduce unnecessary padding vectors in word embeddings. Hence clean them before saving it to the database.
- Additionally, scrape additional contents like some tags etc if they will be useful for searching in elasticsearch database.

**Comment by dhaneshragu** [comment]
> I would like to take up the issue
@Tushar98644 however, i would suggest to wait till #17 is completed because this issue might create merge conflicts with that mentioned issue.

**Comment by botketan** [comment]
@Tushar98644  apologises for the delay you can start working on the issue now

**Comment by dhaneshragu** [comment]
@Tushar98644 any updates?

**Comment by Tushar98644** [comment]
> @Tushar98644 any updates?

haven't started working on it , will update in the next 2 days
