### ISSUE TITLE
Create the frontend for IntranetSearch

### ISSUE THREAD

**Issue by Ashmit-Verma** [swciitg/IntranetSearch#35]
while typing in search
![image](https://github.com/user-attachments/assets/f3affe6e-48f6-4924-8c1e-0130ca6c2990)
on hovering while typing 
![image](https://github.com/user-attachments/assets/a5e206d0-e09f-4277-8ac4-3acaa0529139)
after entering the search
![image](https://github.com/user-attachments/assets/0e94c620-b85c-4014-926d-5cb5b0424118)
the search bar position should be fixed
![image](https://github.com/user-attachments/assets/39874a02-2213-466b-a4ba-cf305f677776)
design for the dark mode for the same
![image](https://github.com/user-attachments/assets/d9f19e24-4f9b-4a09-b401-665fbc75aa8f)
Use react and tailwind for the ui . Make the screens responsive .Try to stick to the design , you can make minor changes according to you like Implement any subtle hover effects or animations

**Comment by TSP06** [comment]
hey @Ashmit-Verma assign me this
