### ISSUE TITLE
Make this page on a different route currently it is scrollable

### ISSUE THREAD

**Issue by durgeshdeo** [swciitg/IntranetSearch#37]
[
![Screenshot 2024-10-23 215314](https://github.com/user-attachments/assets/9e99e782-a8c9-43e5-ae6b-2a9dd649322e)
](url)

**Comment by Bamof25th** [comment]
I am interested to work on this issue . 
/assign

**Comment by TSP06** [comment]
@durgeshdeo created pulll request adressing this issue

**Comment by Pria2601** [comment]
assign to me @durgeshdeo
