### ISSUE TITLE
Setup github actions

### ISSUE THREAD

**Issue by dhaneshragu** [swciitg/IntranetSearch#8]
# GitHub Actions Setup

## Tasks
Setup github actions to:
1. Automatically add the `hacktoberfest-accepted` label to merged pull requests for an issue.
2. Automatically add the `hacktoberfest` and `hacktoberfest2023` labels to newly created issues.
3. Comment assigned, tagging the user as soon as someone is assigned to an issue.

## Context

GitHub Actions can help streamline our development and contribution processes by automating certain repetitive tasks. These tasks, as mentioned above, will be beneficial for tracking contributions related to Hacktoberfest.

**Comment by Anish-Sarawgi** [comment]
Hey @dhaneshragu, i am interested in resolving this issue. Can you suggest me some resources to work on this?

**Comment by dhaneshragu** [comment]
> Hey @dhaneshragu, i am interested in resolving this issue. Can you suggest me some resources to work on this?

You can refer to this link: https://docs.github.com/en/actions/learn-github-actions/

**Comment by Anish-Sarawgi** [comment]
I want to work on this issue. Can you assign it to me?

**Comment by dhaneshragu** [comment]
> Hey @dhaneshragu, I want to work on this issue. Can you assign it to me?

@Anish-Sarawgi assigned it to you.

**Comment by vivekreddy049** [comment]
hey @dhaneshragu i would like to work on this 
i have made  github action for  hacktober and hactober2023 label for new issues 
can you assign it to me ?

**Comment by dhaneshragu** [comment]
Hey @vivekreddy049 , If @Anish-Sarawgi doesn't repond within tomorrow evening, I'll assign this to you.

**Comment by Anish-Sarawgi** [comment]
Hey @dhaneshragu, i have created a PR  to add tags in newly created issues. You can assign the other two GitHub Actions to @vivekreddy049. And please review my PR.

**Comment by dhaneshragu** [comment]
@Anish-Sarawgi , inorder to accept the PR, you have to complete all the given tasks, partial completion can't be accepted.

**Comment by dhaneshragu** [comment]
@vivekreddy049 you are assigned. submit PR within 6th October.

**Comment by harshiitsingh** [comment]
@dhaneshragu I have added a PR regarding this issue. Please have a look.

**Comment by dhaneshragu** [comment]
There is already a PR made by assignee and we're reviewing it.

**Comment by harshiitsingh** [comment]
It's okay. But this issue helped me learn the basics of github actions, so just tried to make a contribution. Thanks.

**Comment by dhaneshragu** [comment]
> It's okay. But this issue helped me learn the basics of github actions, so just tried to make a contribution. Thanks.

@harshiitsingh , all of your 3 issues are not working. kindly test it properly.
